# Generated by Django 3.1 on 2020-09-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('skill', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('uni', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
