# Generated by Django 3.1 on 2020-09-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_account_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='salary',
            field=models.CharField(max_length=10000),
        ),
    ]
